### ISSUE TITLE
BindDomainsCommand is fixed to RRType A and public IP

### ISSUE THREAD

**Issue by gqtan** [ingenieux/beanstalker#54]
Hi,

We had tried out the BindDomains for singleinstances and it works to update the specified domain using the single instance' public IP. However we would like to use the instance' Public DNS of type CNAME instead which this information is also not readily available curEnv variable. Kindly advise if this can be considered in the next release to have option to use Public DNS or Public IP.

Regards,
Gianne

**Comment by aldrinleal** [comment]
SingleInstance is a very different beast, and only suitable for small, non-HA deployments.

Unfortunately, AWS EB is very hard when it comes to HA, ELB and DNS, to the point it makes sense to have something deployed just to ensure you don't lose connections due to bad DNS caches or simply bad deployments at all :)
