### ISSUE TITLE
Replace Environment solution stack is not what I expected

### ISSUE THREAD

**Issue by dlvenable** [ingenieux/beanstalker#55]
We recently attempted to update the solution stack we use for our environments. When viewing the logs I found a warning from the following string (found in ReplaceEnvironmentMojo).

"(btw, we're launching with solutionStack/ set to '%s' instead of the default ('%s'). "
                + "If this is not the case, then we kindly ask you to file a bug report on the mailing list :)",

I took a brief look at the code. It appears that the plugin will get the solution stack from existing environments regardless of what this parameter is set to use. I found this behavior unintuitive. It also will make upgrading solutions stacks much more difficult than simply modifying the Maven POM settings.

**Comment by jedge-mgc** [comment]
@aldrinleal It would be very helpful to be able to change the solution stack on a replace-environment deployment. While this makes perfect since for update environment operations, where the Solution Stack cannot be upgraded anyway, but on a replace-environment when we're spinning up a new parallel stack and intend to swap DNS once it's healthy, it doesn't seem there is any advantage to being prevented from specifying the solution stack to use for the new environment.

**Comment by aldrinleal** [comment]
It is possible (use a wildcard on the solution stack name)

--
-- Aldrin Leal, <aldrin@leal.eng.br>
Master your EC2-fu! Get the latest ekaterminal public beta
http://www.ingenieux.com.br/products/ekaterminal/

**Comment by frankamp** [comment]
@aldrinleal I'm unsure what the wildcard does for us. I don't want to change to a random solution stack that the wildcard matches, I want to specify one for the replacement environment w/ cname swap as @jedge-mgc mentioned.

My example is I'm moving from an old stack:

64bit Amazon Linux 2014.03 v1.0.7 running Tomcat 7 Java 7
to
64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 7 Java 7

How would I specify a wildcard to make this specific transition happen?

**Comment by aldrinleal** [comment]
@frankamp, wouldn't mvn -Pawseb clean deploy -Dbeanstalk.solutionStack='64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 7 Java 7' do the trick?

**Comment by aldrinleal** [comment]
Sorry, ok, let me explain the whole affair so we can sort it out.

## A bit of a rant about me and the world and 'a porra toda':

First, some context: As you guys noticed, I'm a bit away from beanstalker. I admit I lost some motivation, but also it is interesting to draw some context

The AWS Elastic Beanstalk API, afaik, only had a SINGLE change (cname swap I think) over the years, and yet it was in 2010 - the year it was launched. 
I wrote beanstalker circa 8 months later. First, focusing on API coverage and later just decided to offer users power and at the same time, trying to focus on spare time

If you look at all the contributors, I'd say that only five users ever paid me to look and improve it. And only two of those contribute back to beanstalker on a very regular basis. I need to ensure at least that it works cleanly on the current zeitgeist, while at the same time trying to keep a sane release process (and thats why I never focused on overtesting it - Our tests are a mess because of the average runtime length for instance)

So what I do? I focus on the archetypes, snce it allows me to provide a single codebase to not only allow me to  quickly iterate and test, but also catch any showstoppers. 95% of the time, an issue here in Github could be simply solved by creating a version from the latest archetype, and comparing the parameters. Actually, there's an integration testing that just uses the archetypes to achieve that (all voluntary - have you noticed the challenges of writing OSS for paid services like the cloud)

AWS Support? Yes, I paid in order for the issue on the fast-deploy. In fact, I kept a **case open for over three** years, to only hear, after meeting people in Vegas that "-oh, thats an undocumented feature. And deprecated". 

Oh nevermind. You meant AWS Supporting me? My e-mails for assistance were ignored. Any official opinions from AWS personnel so far went from complete silence to even an "its not supported". I know the AWS Trainers like it. AWS Architects try to convince you to go to Eclipse. Good riddance.

The only meeting I've managed from the AWS PM (the two I've met in Person in Vegas also didn't return my e-mails). To sum up his answer:

| ... was never intended to be an external service. It was simply an implementation detail for EB to 
| enable incremental deployments from the CLI and the Eclipse/Visual Studio toolkits. Given, the new
| CodeCommit service, it would be better for EB to use that service for incremental deployments.
| Also, have you looked in to the new CodePipeline service? Seems like a combination of
| CodePipeline and CodeCommit will enable a fully integrated CI/CD pipeline for EB.

So thats AWS Vision for CI/CD. And the whole reason I started this was bc I feel more at home on Windows, would you believe it?

So consider I'm just making this whole thing in full maintenance, yet that some users interactions to me are sometimes interpreted by me as impacient. So, my official answer for now is: "Oh, its not working? Don't worry, use AWS Toolkit for Eclipse!", or the Jenkins Plugin from the User that tried to remove me from the project because I didn't accept his contributions.

Has any one ever donated documentation? It also helps. But, I've had once a very rude user complaining. And I sent him a personal note anking for him to fix. My answer was: "-I'm too busy"

Yeah.

Enough rant.

## Back to AWS Elastic Beanstalk

And what changed from 2010 until now? One would launch, but it basically changes only two things:

  * the list of available solution stacks
  * the RUNTIME PARAMETERS of their solution stacks

An environment is a life organism, and their parameters are inicially overwritten by you, but also defaults from the solution stack. So actually I forgot the reason why I did have that line. And it  was easy:

If I allowed you guys to do this, I wouldn't have any peace of mind. Any undocumented parameters would require a new release, and I'd need to maintain the blacklist of options (when we started back in 2011, there were only one or two stacks. Today, I just noticed there are close to one hundred. And I never told you could only do it in Java btw :)

Oh, make it optional as a parameter. Have you guys noticed how hard is just to make sense of the AWS Documentation? Look at [all the possible parameters](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html). 

And try to envision there's over a thousand. Now go ask AWS to support it in Eclipse, will you? And please send me a picture of yourself when you see their reply (if you manage to get one).

## So, tell us about that Warning

Why? I uncommented that line that you guys mentioned (btw, any users complaining about "-Why it was not released?", I suggest to learn a magical mvn command called 'mvn install' ffs) so remember what happens.

```
[INFO] --- beanstalk-maven-plugin:1.4.1-SNAPSHOT:replace-environment (default-cli) @ post-to-sns ---
[INFO] Creating a new environment on post-to-sns-prod-0.elasticbeanstalk.com
[INFO] Including Option Setting: aws:autoscaling:asg:Availability Zones['Any']
[INFO] Including Option Setting: aws:autoscaling:asg:Cooldown['360']
[INFO] Excluding Option Setting: aws:autoscaling:asg:Custom Availability Zones['']
[INFO] Including Option Setting: aws:autoscaling:asg:MaxSize['1']
[INFO] Including Option Setting: aws:autoscaling:asg:MinSize['1']
[INFO] Excluding Option Setting: aws:autoscaling:launchconfiguration:BlockDeviceMappings['']
[INFO] Including Option Setting: aws:autoscaling:launchconfiguration:EC2KeyName['aldrin@leal.eng.br']
[INFO] Including Option Setting: aws:autoscaling:launchconfiguration:IamInstanceProfile['aws-elasticbeanstalk-ec2-role']
[INFO] Including Option Setting: aws:autoscaling:launchconfiguration:ImageId['ami-901ba3f8']
[INFO] Including Option Setting: aws:autoscaling:launchconfiguration:InstanceType['m1.small']
[INFO] Including Option Setting: aws:autoscaling:launchconfiguration:MonitoringInterval['5 minute']
[INFO] Excluding Option Setting: aws:autoscaling:launchconfiguration:RootVolumeIOPS['']
[INFO] Excluding Option Setting: aws:autoscaling:launchconfiguration:RootVolumeSize['']
[INFO] Excluding Option Setting: aws:autoscaling:launchconfiguration:RootVolumeType['']
[INFO] Including Option Setting: aws:autoscaling:launchconfiguration:SSHSourceRestriction['tcp,22,22,0.0.0.0/0']
[INFO] Excluding Option Setting: aws:autoscaling:launchconfiguration:SecurityGroups['awseb-e-azsmstd5qu-stack-AWSEBSecurityGroup-1KHFNNJQDIOIO']
[INFO] Excluding Option Setting: aws:autoscaling:updatepolicy:rollingupdate:MaxBatchSize['']
[INFO] Excluding Option Setting: aws:autoscaling:updatepolicy:rollingupdate:MinInstancesInService['']
[INFO] Excluding Option Setting: aws:autoscaling:updatepolicy:rollingupdate:PauseTime['']
[INFO] Including Option Setting: aws:autoscaling:updatepolicy:rollingupdate:RollingUpdateEnabled['false']
[INFO] Including Option Setting: aws:autoscaling:updatepolicy:rollingupdate:RollingUpdateType['Time']
[INFO] Including Option Setting: aws:autoscaling:updatepolicy:rollingupdate:Timeout['PT30M']
[INFO] Excluding Option Setting: aws:cloudformation:template:parameter:AppSource['https://s3.amazonaws.com/elasticbeanstalk-samples-us-east-1/docker-sample-v3.zip']
[INFO] Excluding Option Setting: aws:cloudformation:template:parameter:DockerDEB['']
[INFO] Including Option Setting: aws:cloudformation:template:parameter:DockerProxyServer['nginx']
[INFO] Including Option Setting: aws:cloudformation:template:parameter:DockerRPM['https://s3.amazonaws.com/elasticbeanstalk-env-resources-us-east-1/stalks/eb_docker_3.1.1/lib/docker-1.2.0-2.20.amzn1.x86_64.rpm']
[INFO] Including Option Setting: aws:cloudformation:template:parameter:EnvironmentVariables['PARAM3=,PARAM4=,PARAM1=,PARAM2=,PARAM5=,AWS_SECRET_KEY=,AWS_ACCESS_KEY_ID=']
[INFO] Including Option Setting: aws:cloudformation:template:parameter:HooksPkgUrl['https://s3.amazonaws.com/elasticbeanstalk-env-resources-us-east-1/stalks/eb_docker_3.1.1/lib/hooks.tar.gz']
[INFO] Including Option Setting: aws:cloudformation:template:parameter:InstancePort['80']
[INFO] Excluding Option Setting: aws:ec2:vpc:AssociatePublicIpAddress['']
[INFO] Excluding Option Setting: aws:ec2:vpc:Subnets['']
[INFO] Excluding Option Setting: aws:ec2:vpc:VPCId['']
[INFO] Including Option Setting: aws:elasticbeanstalk:application:Application Healthcheck URL['/health/check']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:AWS_ACCESS_KEY_ID['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:AWS_SECRET_KEY['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:PARAM1['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:PARAM2['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:PARAM3['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:PARAM4['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:application:environment:PARAM5['']
[INFO] Including Option Setting: aws:elasticbeanstalk:command:BatchSize['100']
[INFO] Including Option Setting: aws:elasticbeanstalk:command:BatchSizeType['Percentage']
[INFO] Including Option Setting: aws:elasticbeanstalk:command:IgnoreHealthCheck['false']
[INFO] Including Option Setting: aws:elasticbeanstalk:command:Timeout['600']
[INFO] Including Option Setting: aws:elasticbeanstalk:control:DefaultSSHPort['22']
[INFO] Including Option Setting: aws:elasticbeanstalk:control:LaunchTimeout['0']
[INFO] Including Option Setting: aws:elasticbeanstalk:control:LaunchType['Migration']
[INFO] Including Option Setting: aws:elasticbeanstalk:control:RollbackLaunchOnFailure['false']
[INFO] Including Option Setting: aws:elasticbeanstalk:environment:EnvironmentType['SingleInstance']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:environment:ServiceRole['']
[INFO] Including Option Setting: aws:elasticbeanstalk:hostmanager:LogPublicationControl['false']
[INFO] Including Option Setting: aws:elasticbeanstalk:monitoring:Automatically Terminate Unhealthy Instances['true']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:sns:topics:Notification Endpoint['']
[INFO] Including Option Setting: aws:elasticbeanstalk:sns:topics:Notification Protocol['email']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:sns:topics:Notification Topic ARN['']
[INFO] Excluding Option Setting: aws:elasticbeanstalk:sns:topics:Notification Topic Name['']
[INFO] And it'll be named post-to-sns-prod-0
[WARNING] FAILURE
org.apache.maven.plugin.MojoFailureException: Failed
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.handleException(AbstractAWSMojo.java:394)
        at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.handleException(BaseCommand.java:83)
        at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.execute(BaseCommand.java:75)
        at br.com.ingenieux.mojo.beanstalk.env.CreateEnvironmentMojo.createEnvironment(CreateEnvironmentMojo.java:299)
        at br.com.ingenieux.mojo.beanstalk.env.ReplaceEnvironmentMojo.executeInternal(ReplaceEnvironmentMojo.java:200)
        at br.com.ingenieux.mojo.aws.AbstractAWSMojo.execute(AbstractAWSMojo.java:357)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.amazonaws.AmazonServiceException: Configuration validation exception: Unknown or duplicate parameter: DockerRPM (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: ConfigurationValidationException; Request ID: d51b311d-5838-11e5-b311-211dc5f90da2)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
        at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.invoke(AWSElasticBeanstalkClient.java:1826)
        at com.amazonaws.services.elasticbeanstalk.AWSElasticBeanstalkClient.createEnvironment(AWSElasticBeanstalkClient.java:418)
        at br.com.ingenieux.mojo.beanstalk.cmd.env.create.CreateEnvironmentCommand.executeInternal(CreateEnvironmentCommand.java:82)
        at br.com.ingenieux.mojo.beanstalk.cmd.env.create.CreateEnvironmentCommand.executeInternal(CreateEnvironmentCommand.java:28)
        at br.com.ingenieux.mojo.beanstalk.cmd.BaseCommand.execute(BaseCommand.java:73)
        ... 25 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:21 min
[INFO] Finished at: 2015-09-11T00:54:46-03:00
[INFO] Final Memory: 27M/108M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal br.com.ingenieux:beanstalk-maven-plugin:1.4.1-SNAPSHOT:replace-environment (default-cli) on project post-to-sns: Failed: Configuration validation exception: Unknown or duplicate parameter: DockerRPM (Service:
AWSElasticBeanstalk; Status Code: 400; Error Code: ConfigurationValidationException; Request ID: d51b311d-5838-11e5-b311-211dc5f90da2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Simple, the parameters would get messed up and the secondary environment wouldn't start because replace environment copies and filters parameters. I'd need to re-release the builds with an updated list (btw, I haven't touched this code for 9 months and the world didn't fall). Or keep a wiki of the options to blacklist. And hope my users would be able to maintain and keep up with that.

##  Ok, so what would be a good alternative?

I need to strive between making the hard possible and the impossible doable. Replace Environment is a marvel and even if stack upgrades aren't automate-able, I believe there's lot of pain avoiding effort. For me, not having pain is just as good as having pleasure.

In the ideal world, it would be easy to spot by the namespace what is copiable and whatsnot. However, we live in the real world, when there's no real AWS Support and Documentation, and I'm left alone in a Maze surrounded by Unfriendly persons :)

I'll never comment that code again, as I just reminded it was pandoras' box about to open.

## So?

No.

**Comment by frankamp** [comment]
Epic rant! :clap: :clap: :clap:  :-) Thanks for working on this project.

**Comment by aldrinleal** [comment]
@frankamp,

![img_20150825_144917](https://cloud.githubusercontent.com/assets/253109/9807495/66763b6a-582a-11e5-8d59-91de64c40e1d.jpg)

**Comment by jwilmoth** [comment]
I have a similar desire to go from EB platform version X to version Y w/out having to terminate the target environment or manually upgrade the target env via the console (which reaches a scalability limit at a certain number of EB apps). A forced override flag would be a totally workable solution.

**Comment by aldrinleal** [comment]
jwilmoth,

Which part of 'No' you had problems understanding?



--
-- Aldrin Leal, <aldrin@leal.eng.br> / http://about.me/aldrinleal

**Comment by jwilmoth** [comment]
Hi @aldrinleal,

I think this maven plugin is great and I am volunteering to contribute back to the project.  Are you saying "no" to the approach of a forced override which you proposed in Oct?  "No" to supporting platform changes within the replace-environment mojo?  "No" to modifications of any sort to the replace-environment mojo?  "No" to future modifications of the plugin at all?  "No" to contributions from external sources?  I'd still like to improve the project and help fill a need that myself and others have expressed if that's an option.

**Comment by aldrinleal** [comment]
Have you read my post? I mentioned that overriding it wouldnt work and
explained the reason (meaning #1 and #2)

otherwise, be my guest. I am open to a well written and documented patch.
Id suggest cloning replace-environment as, say, upgrade-environment though

**Comment by jwilmoth** [comment]
I've submitted a PR that introduces a new configuration option on the replace-environment goal to override the default/current behavior to force a new solution stack to be used.  I manually tested this and was able to upgrade an EB env from "64bit Amazon Linux 2015.03 v1.4.6 running Docker 1.6.2" —> "64bit Amazon Linux 2015.03 v2.0.2 running Docker 1.7.1".

**Comment by aldrinleal** [comment]
@jwilmoth, I'll accept it as long as you sign a disclaimer accepting all the responsibility for opening the releasing all the worlds' evil by opening the Pandora Box. By accepting, this means I'll fwd and copy all the requests ok? :)

(and ensure you subscribe the beanstalker mailing lists)

**Comment by jwilmoth** [comment]
I'll gladly update the docs for the property with known consequences of overriding the default behavior.   Do you have specific scenarios in mind?   The good news is the PR maintains the existing behavior and one has to consciously configure the new behavior.

**Comment by aldrinleal** [comment]
I did, like the one I shown in the original post I've made. But lets keep
it, then

--
-- Aldrin Leal, <aldrin@leal.eng.br> / http://about.me/aldrinleal
